name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 21 (Zulu)
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "21"

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Create local.properties
        run: |
          echo "PRODUCTION_MODE=${{ secrets.PRODUCTION_MODE }}" >> $GITHUB_WORKSPACE/local.properties
          echo "API_URL=${{ secrets.API_URL }}" >> $GITHUB_WORKSPACE/local.properties
          echo "API_URL_PROD=${{ secrets.API_URL_PROD }}" >> $GITHUB_WORKSPACE/local.properties
          echo "ARTICLE_URL=${{ secrets.ARTICLE_URL }}" >> $GITHUB_WORKSPACE/local.properties

      - name: Build with Gradle
        run: ./gradlew assembleRelease

      - name: List output directory
        run: ls -R app/build/outputs/apk/release

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: app-release-unsigned.apk
          path: app/build/outputs/apk/release/app-release-unsigned.apk

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download APK
        uses: actions/download-artifact@v2
        with:
          name: app-release-unsigned.apk
          path: app-release-unsigned.apk

      - name: Get the latest tag
        id: get_latest_tag
        run: |
          latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1) 2>/dev/null || echo "v0.0.0")
          echo "latest_tag=$latest_tag" >> $GITHUB_ENV
        shell: bash

      - name: Generate new version
        id: generate_version
        run: |
          latest_tag=${{ env.latest_tag }}
          IFS='.' read -r -a version_parts <<< "${latest_tag#v}"
          major=${version_parts[0]}
          minor=${version_parts[1]}
          patch=${version_parts[2]}
          new_patch=$((patch + 1))
          new_version="v$major.$minor.$new_patch"
          echo "version=$new_version" >> $GITHUB_ENV
        shell: bash

      - name: Check if tag exists
        id: check_tag
        run: |
          if git rev-parse "refs/tags/${{ env.version }}" >/dev/null 2>&1; then
            echo "Tag ${{ env.version }} exists."
            echo "TAG_EXISTS=true" >> $GITHUB_ENV
          else
            echo "Tag ${{ env.version }} does not exist."
            echo "TAG_EXISTS=false" >> $GITHUB_ENV
        shell: bash

      - name: Generate unique version if tag exists
        if: env.TAG_EXISTS == 'true'
        run: |
          version=${{ env.version }}
          while git rev-parse "refs/tags/$version" >/dev/null 2>&1; do
            IFS='.' read -r -a version_parts <<< "${version#v}"
            patch=${version_parts[2]}
            new_patch=$((patch + 1))
            version="v${version_parts[0]}.${version_parts[1]}.$new_patch"
          done
          echo "unique_version=$version" >> $GITHUB_ENV

      - name: Set version to unique version if needed
        if: env.TAG_EXISTS == 'true'
        run: |
          echo "version=${{ env.unique_version }}" >> $GITHUB_ENV

      - name: Create new Git tag
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git tag ${{ env.version }}
          git push origin ${{ env.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.version }}
          release_name: Release ${{ env.version }}
          draft: false
          prerelease: false

      - name: Upload APK to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./app-release-unsigned.apk
          asset_name: app-release-unsigned.apk
          asset_content_type: application/vnd.android.package-archive
